---

- hosts: k3s_cluster
  gather_facts: yes

  roles:
    - role: prereq
      become: yes
    - role: download
      become: yes

- hosts: master
  roles:
    - role: k3s/master
      become: yes

- hosts: node
  roles:
    - role: k3s/node
      become: yes

- hosts: k3s_cluster
  roles:
    - role: k3s/post
      become: true
