---
- name: Create manifests directory on first master
  file:
    path: /var/lib/rancher/k3s/server/manifests
    state: directory
    owner: root
    group: root
    mode: 0644
  when: ansible_hostname == hostvars[groups['master'][0]]['ansible_hostname']

- name: Copy ingress-nginx chart to first master
  template:
    src: "ingress-nginx.yaml.j2"
    dest: "/var/lib/rancher/k3s/server/manifests/ingress-nginx.yaml"
    owner: root
    group: root
    mode: 0644
  when: ansible_hostname == hostvars[groups['master'][0]]['ansible_hostname']
