---

- name: Deploy prometheus-operator manifest
  include_tasks: prometheus-operator.yml

- name: Deploy ingress-nginx manifest
  include_tasks: ingress-nginx.yml

- name: Deploy kubernetes-dashboard manifest
  include_tasks: kubernetes-dashboard.yml

- name: debug extra_server_args
  debug:
    msg: 
      - "{{ extra_server_args }}"

- name: Copy K3s service file
  register: k3s_service
  template:
    src: "k3s.service.j2"
    dest: "{{ systemd_dir }}/k3s.service"
    owner: root
    group: root
    mode: 0644

- name: Enable and check K3s service
  systemd:
    name: k3s
    daemon_reload: yes
    state: restarted
    enabled: yes

- name: Wait for node-token
  wait_for:
    path: "{{ k3s_server_location }}/server/node-token"

- name: Register node-token file access mode
  stat:
    path: "{{ k3s_server_location }}/server/node-token"
  register: p

- name: Change file access node-token
  file:
    path: "{{ k3s_server_location }}/server/node-token"
    mode: "g+rx,o+rx"

- name: Read node-token from master
  slurp:
    path: "{{ k3s_server_location }}/server/node-token"
  register: node_token

- name: Store Master node-token
  set_fact:
    token: "{{ node_token.content | b64decode | regex_replace('\n', '') }}"

- name: Restore node-token file access
  file:
    path: "{{ k3s_server_location }}/server/node-token"
    mode: "{{ p.stat.mode }}"

- name: Create directory .kube
  file:
    path: "{{ ansible_user_dir }}/.kube"
    state: directory
    owner: "{{ ansible_user_id }}"
    mode: "u=rwx,g=rx,o="

- name: Copy config file to user home directory
  copy:
    src: /etc/rancher/k3s/k3s.yaml
    dest: "{{ ansible_user_dir }}/.kube/config"
    remote_src: yes
    owner: "{{ ansible_user_id }}"
    mode: "u=rw,g=,o="

- name: Replace https://localhost:6443 by https://master-ip:6443
  command: >-
    k3s kubectl config set-cluster default
      --server=https://{{ master_ip }}:6443
      --kubeconfig {{ ansible_user_dir }}/.kube/config
  changed_when: true

- name: Create kubectl symlink
  file:
    src: /usr/local/bin/k3s
    dest: /usr/local/bin/kubectl
    state: link

- name: Create crictl symlink
  file:
    src: /usr/local/bin/k3s
    dest: /usr/local/bin/crictl
    state: link

- name: Create ctr symlink
  file:
    src: /usr/local/bin/k3s
    dest: /usr/local/bin/ctr
    state: link

# - name: Get contents of manifests folder
#   find:
#     paths: /var/lib/rancher/k3s/server/manifests
#     file_type: file
#   register: k3s_server_manifests

# - name: Get sub dirs of manifests folder
#   find:
#     paths: /var/lib/rancher/k3s/server/manifests
#     file_type: directory
#   register: k3s_server_manifests_directories

# - name: Remove manifests and folders that are only needed for bootstrapping cluster so k3s doesn't auto apply on start
#   file:
#     path: "{{ item.path }}"
#     state: absent
#   with_items:
#     - "{{ k3s_server_manifests.files }}"
#     - "{{ k3s_server_manifests_directories.files }}"
#   loop_control:
#     label: "{{ item.path }}"
